# Notas de curso manejo de datos con mumpy y pandas platzi

## NumPy

* Se instala con el comando pip install numpy
* Se importa con el comando import numpy as np


### Array de numpy

* Es la estructura central de NumPy
* Representa datos de una manera estructurada
* Indexado que facilita la consulta de datos
* Facilita el acceso a uno o muchos elementos


In [11]:
# importar numpy
import numpy as np


In [12]:
# crear una lista corriente de python
lista = [1,2,3,4,5,6,7,8,9]
lista


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
# llevar la lista a un array de python
arr = np.array(lista)


In [14]:
# se crea una matriz con listas de python
matriz = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

# se convierte la matriz en array
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Indexing
Se usa para acceder a una posición específica del array

In [15]:
# los indexados se manejan con posiciones en el array y empiezan desde cero

arr[0] # devuelve la primera posicion del array

1

In [16]:
# cuando son array que vienen de matrices [0] devuelve la primera fila
matriz[0]


array([1, 2, 3])

In [17]:
# para acceder a un valor especifico fila, columna se pone [fila, columna]
matriz[0,2] # devuelve de la primera fila, el tercer elemento

3

#### Slicing
Se usa para acceder a varios valores de un array al tiempo

In [19]:
# selecciona desde la posicion inicio hasta fin menos uno [inicio:fin], así [0,3] devuelve desde la posicion cero hasta la posicion 2
arr[0:3]

array([1, 2, 3])

In [20]:
# Si no se indica un valor de inicio, devuleve desde la posicion cero 
arr[:5]

array([1, 2, 3, 4, 5])

In [21]:
# Si no se indica un valor de fin, devuleve desde la posicion inicio hasta la ultima posicion
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
# Si no se indica inicio ni fin devuelve todo
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Tambien se puede usar slicing en matrices [inicio:fin, inicio:fin] a la izquierda de la coma son las filas y a la derecha de la coma son las columnas
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])