# Notas de curso manejo de datos con NumPy y Pandas

## NumPy

* Se instala con el comando pip install numpy
* Se importa con el comando import numpy as np


### Array de numpy

* Es la estructura central de NumPy
* Representa datos de una manera estructurada
* Indexado que facilita la consulta de datos
* Facilita el acceso a uno o muchos elementos


In [1]:
# importar numpy
import numpy as np


In [2]:
# crear una lista corriente de python
lista = [1,2,3,4,5,6,7,8,9]
lista


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# llevar la lista a un array de python
arr = np.array(lista)


In [4]:
# se crea una matriz con listas de python
matriz = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

# se convierte la matriz en array
matriz = np.array(matriz)
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Indexing
Se usa para acceder a una posición específica del array

In [5]:
# los indexados se manejan con posiciones en el array y empiezan desde cero

arr[0] # devuelve la primera posicion del array


1

In [6]:
# cuando son array que vienen de matrices [0] devuelve la primera fila
matriz[0]


array([1, 2, 3])

In [7]:
# para acceder a un valor especifico fila, columna se pone [fila, columna]
matriz[0,2] # devuelve de la primera fila, el tercer elemento


3

#### Slicing
Se usa para acceder a varios valores de un array al tiempo

In [8]:
# selecciona desde la posicion inicio hasta fin menos uno [inicio:fin], así [0,3] devuelve desde la posicion cero hasta la posicion 2
arr[0:3]


array([1, 2, 3])

In [9]:
# Si no se indica un valor de inicio, devuleve desde la posicion cero 
arr[:5]


array([1, 2, 3, 4, 5])

In [10]:
# Si no se indica un valor de fin, devuleve desde la posicion inicio hasta la ultima posicion
arr[2:]


array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# Si no se indica inicio ni fin devuelve todo
arr[:]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Tambien se puede usar slicing en matrices [inicio:fin, inicio:fin] a la izquierda de la coma son las filas y a la derecha de la coma son las columnas
matriz[1:,0:2]


array([[4, 5],
       [7, 8]])

### Tipos de datos en NumPy
Se usa la propiedad dtype de los objetos array, también se puede usar el método astype(np.tipo_dato), todo el array queda con el mismo tipo de dato, no se pueden mezclar número y texto

In [13]:
# se crea un array
arr = np.array([1, 2, 3, 4])
arr


array([1, 2, 3, 4])

In [14]:
# dtype devuleve el tipo de dato que esta almacenado
arr.dtype


dtype('int64')

In [15]:
# Se puede definir el dtype al crear el array
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype


dtype('float64')

In [16]:
# tambien se puede definir el tipo con el metodo astype
arr2 = np.array([1, 2, 3, 4])
arr2 = arr2.astype(np.float64)
arr2.dtype


dtype('float64')

### Dimensiones en NumPy
Se accede al número de dimensiones con la propiedad ndim de los array
* Escalar, cuando es solo un valor o dimensión 0
* Vector, cuando es una fila o una columna dimmensión 1
* Matriz, cuando es fila y columna hasta la dimensión 3
* Tensor, cuando tiene dimensión n,n

In [17]:
# definir un escalar
escalar = np.array(42)
print(escalar)
print('dimensión: '+ str(escalar.ndim))


42
dimensión: 0


In [18]:
# definir un vector
vector = np.array([1,2,3])
print(vector)
print('dimensión: '+ str(vector.ndim))


[1 2 3]
dimensión: 1


In [19]:
# definir una matriz
matriz2 = np.array([[1,2,3],[4,5,6]])
print(matriz2)
print('dimensión: '+ str(matriz2.ndim))


[[1 2 3]
 [4 5 6]]
dimensión: 2


In [20]:
# definir un tensor
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print('dimensión: '+ str(tensor.ndim))


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimensión: 3


#### Agregar o quitar dimensiones
Se pueden definir el número de dimensiones desde el inicio o agregar a un objeto que ya existe

In [21]:
# en este ejemplo se esta definiendo un tensor de tres dimensiones
tensor_3d = np.array([1,2,3], ndmin=3)
print(tensor_3d)
print('dimensión: '+ str(tensor_3d.ndim))


[[[1 2 3]]]
dimensión: 3


In [22]:
# en este ejemplo se expande la dimension de un vector ya creado
matriz_2d = np.expand_dims(vector, axis=0) #axis 0 es fila, axis 1 es columna
print(matriz_2d)
print('dimensión: '+ str(matriz_2d.ndim))


[[1 2 3]]
dimensión: 2


Con la funcion np.squeeze() se dejan los datos con el número de dimensiones que se están usando

In [23]:
# vamos a quitarle la dimension que tiene de mas matriz_2d
print(matriz_2d, matriz_2d.ndim)
vector_1d = np.squeeze(matriz_2d)
print(vector_1d, vector_1d.ndim)


[[1 2 3]] 2
[1 2 3] 1


### Creando arrays con NumPy
* para rango de valores np.arange(inicio, fin, step)
* para crear un array lleno de ceros np.zeros((nfilas, ncolumnas))
* para crear un array lleno de unos np.ones((nfilas, ncolumnas))
* para crear un array con valor inicio, valor final y cuantos valores en ese rango np.linespace(v_inicio, v_final, cantidad_valores)
* para crear una matriz cuadrada con la diagonal con valores 1 np.eye(valor)
* para crear un array con x cantidad de valores aleatorios entre cero y uno np.random.rand(x)
* para crear una matriz con x cantidad de filas e y cantidad de columnas con valores aleatorios entre cero y uno np.random.rand(nfilas, ncolumnas)
* para generar un valor aleatorio en un rango de datos dado np.random.randint(min, max)
* para generar una matriz con nfilas, mcolumnas y valores aleatorios en un rango dado np.random.randint(min, max,(nfilas,ncolumnas))

In [24]:
# crear un rango de valores con python, sin usar numpy
list(range(0,10)) # crea lista con valores de 0 a 9


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
# crear rango con numpy
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# crear rango con numpy usando step
np.arange(0,10,2) # crea un array con valores entre cero y 9, de dos en dos, el resultado es 0,2,4,6,8


array([0, 2, 4, 6, 8])

In [27]:
# crear un vector con cinco ceros
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [28]:
# crear una matriz de 3x3 con ceros
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# crear una matriz de 3x3 con unos
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# vector con 5 datos que empieza en cero y termina en 10
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
# crea una matriz de 4x4 con la diagonal 1
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# genera un array de 4 valores aleatorios entre 0 y 1
np.random.rand(4)


array([0.57297326, 0.98490071, 0.14094141, 0.6864438 ])

In [33]:
# genera una matriz de 4x4 con valores aleatorios entre 0 y 1
np.random.rand(4,4)


array([[0.92968108, 0.78181477, 0.41281001, 0.92951378],
       [0.91049897, 0.48140625, 0.27552649, 0.21380653],
       [0.61699259, 0.91661604, 0.8660706 , 0.37620439],
       [0.12733865, 0.2075296 , 0.0751989 , 0.81183246]])

In [34]:
# genera un valor aleatorio en n rango dado
np.random.randint(1, 15)


7

In [35]:
# genera una matriz de 4x4 con valores aleatorios en un rango entre 1 y 15
np.random.randint(1,15,(4,4))

array([[ 9,  8,  4, 10],
       [14, 13,  6,  3],
       [ 9,  2, 12, 10],
       [13,  8,  4,  5]])

### Modificar dimensiones de arrays con NumPy - shape y reshape
Al modificar los array debe mantener la cantidad de datos inicial nfilas x mcolumnas
* la propiedad shape me dice numero de filas y columnas
* el método reshape sirve para cambiar las dimensiones del array
* se puede usar también la función np.reshape(array, (nfilas, ncolumnas), 'lenguaje')

In [36]:
# crea un array de 3x2 con valores aleatorios entre 1 y 10
arr = np.random.randint(1,10,(3,2))
arr


array([[1, 9],
       [2, 4],
       [9, 1]])

In [37]:
# conocer numero de filas y columnas
arr.shape


(3, 2)

In [38]:
# cambiar array de 3x2 a 1x6
arr.reshape(1,6)


array([[1, 9, 2, 4, 9, 1]])

In [39]:
arr

array([[1, 9],
       [2, 4],
       [9, 1]])

In [40]:
# cambia el array de 3x2 a 1x6 como lo haría el lenguaje C, que organiza por filas
np.reshape(arr, (1,6), 'C')


array([[1, 9, 2, 4, 9, 1]])

In [41]:
# cambia el array de 3x2 a 1x6 como lo haría el lenguaje Fortrant, que organiza por columnas
np.reshape(arr, (1,6), 'F')


array([[1, 2, 9, 9, 4, 1]])

### Funciones principales de NumPy
* obtener valores máximos array.max()
* obtener valores máximos por fila array.max(1)
* obtener valores máximos por columna array.max(0)
* obtener el índice o posición de donde se encuentra el valor máximo del array array.argmax()
* obtener valores mínimos array.max()
* obtener valores mínimos por fila array.max(1)
* obtener valores mínimos por columna array.max(0)
* obtener el índice o posición de donde se encuentra el valor mínimo del array array.argmin()
* obtener la distancia entre el valor máximo y mínimos del array array.ptp()
* organizar los datos de menor a mayor array.sort()
* para concatenar dos array deben tener las mismas dimensiones np.concatenate((array_1, array_2),axis=) axis=0 es por fila, axis=1 es por columna


In [42]:
# se crea un array
arr = np.random.randint(1,20,10)
arr

array([10, 19, 18,  2,  2, 14,  6,  4, 15, 12])

In [43]:
# convertir en matriz el array
matriz = arr.reshape(2,5)
matriz

array([[10, 19, 18,  2,  2],
       [14,  6,  4, 15, 12]])

In [44]:
# obtener maximo de todo el conjunto de datos
print(arr.max())
print(matriz.max())


19
19


In [45]:
# obtener maximo por filas d ela matriz
matriz.max(1)


array([19, 15])

In [46]:
# obtener el maximo por columnas
matriz.max(0)


array([14, 19, 18, 15, 12])

In [47]:
# obtiene la posicion en donde se encuentra el valor maximo
arr.argmax()


1

In [48]:
# obtiene la posicion en donde se encuentra el valor maximo
matriz.argmax()


1

In [49]:
matriz


array([[10, 19, 18,  2,  2],
       [14,  6,  4, 15, 12]])

In [50]:
# obtener la distancia entre el valor maximo y minimo de la matriz, es como obtener el rango
matriz.ptp()


17

In [51]:
# obtiene la distancia entre el valor maximo y minimo de la matriz por filas
matriz.ptp(1)

array([17, 11])

In [52]:
# obtiene la distancia entre el valor maximo y minimo de la matriz por columnas
matriz.ptp(0)

array([ 4, 13, 14, 13, 10])

In [53]:
# organiza los datos del array de menor a mayor
arr.sort()
arr

array([ 2,  2,  4,  6, 10, 12, 14, 15, 18, 19])

In [54]:
# crear dos array por fila
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
a.ndim


2

In [55]:
# aumentar una dimension de b para luego concatenar por fila con a
b = np.expand_dims(b,0)
b.ndim

2

In [56]:
# concatenar a y b por fila
c = np.concatenate((a,b),axis=0) #axis=0 indica que es por fila
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
# concatenar a y b por columna, se debe transponer b
d = np.concatenate((a, b.T), axis=1) # axis=1 indica que es por columna
d

array([[1, 2, 5],
       [3, 4, 6]])

### Copiar un array con NumPy
Numpy asigna un solo sitio en memoria a un array. Si se asigna otro nombre al mismo array y se modifica uno de los dos, se modificarán ambos.
Para que eso no pase se usa la función .copy() que crea una copia de los datos para no modificar el original

In [58]:
# se crea un array con veinte elementos aleatorios entre 1 y 10
arr = np.random.randint(1,10, 20)
arr

array([2, 5, 9, 9, 9, 9, 7, 9, 3, 1, 4, 2, 9, 8, 5, 7, 1, 8, 6, 3])

In [59]:
# se crea otro array con los primeros cinco valores de arr
parte_arr = arr[0:6]
parte_arr

array([2, 5, 9, 9, 9, 9])

In [60]:
# se modifican los cinco valores de parte_arr por ceros
parte_arr[:] = 0
parte_arr

array([0, 0, 0, 0, 0, 0])

In [61]:
# se valida que arr tambien cambio al modificar parte_arr
arr

array([0, 0, 0, 0, 0, 0, 7, 9, 3, 1, 4, 2, 9, 8, 5, 7, 1, 8, 6, 3])

In [62]:
# para no modificar arr se debe hacer una copia con .copy()
parte_arr2 = arr[0:6].copy()
parte_arr2

array([0, 0, 0, 0, 0, 0])

In [63]:
# modifico parte_arr2 asignando los valores de 5
parte_arr2[:] = 5
parte_arr2

array([5, 5, 5, 5, 5, 5])

In [64]:
# valido de arr no ha cambiado
arr

array([0, 0, 0, 0, 0, 0, 7, 9, 3, 1, 4, 2, 9, 8, 5, 7, 1, 8, 6, 3])

### Condiciones con NumPy
Sirve para seleccionar datos con una condición dada y modificar valores si se requiere

In [65]:
# se crea un array con 10 datos y valores entre 1 y 10
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [66]:
# validar cuales valores del array son mayores que 5
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [67]:
# crea array con los que son mayores de 5
condicion = arr>5
otro_array = arr[condicion]
otro_array

array([ 6,  7,  8,  9, 10], dtype=int8)

In [68]:
# agregar mas de una condicion
condicion2 = (arr>5) & (arr<9)
otro_array2 = arr[condicion2]
otro_array2

array([6, 7, 8], dtype=int8)

In [69]:
# modificar valores que cumplen una condicion dada
arr[condicion2] = 4 
arr

array([ 1,  2,  3,  4,  5,  4,  4,  4,  9, 10], dtype=int8)

### Operaciones con NumPy


In [70]:
# se crean dos vectores con valores de 1 a 9
arr = np.arange(1,10)
arr2 = arr.copy()
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# sumar dos vectores
arr + arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
# multiplicar dos vectores
arr * arr2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [73]:
# convertir a matriz 
matriz = arr.reshape(3,3)
matriz2 = matriz.copy()
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
# sumar uno a uno los elementos de dos matrices
matriz + matriz2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [75]:
# multiplicar uno a uno los elementos de dos matrices
matriz * matriz2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [76]:
# producto matricial o producto punto, para resolver este producto el numero de filas de la priera matriz debe ser igual al numero de columnas de la segunda matriz
np.matmul(matriz,matriz2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [77]:
# otra forma de producto punto con el uso de @
matriz @ matriz2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## Pandas
* Pandas Series: es un arreglo unidimensional indexado, permite búsqueda por índice y también hacer Slicing, es parecido a un vector de NumPy, se pueden realizar operaciones aritméticas y permite el almacenamiento de distintos de datos, no solo numéricos, en esto se diferencia de NumPy ya que puede tener en la misma serie tipos de datos distintos
* Pandas DataFrame: Es la estructura principal de Pandas, es un arreglo de dos dimensiones, permite búsqueda por índice (columnas o filas), los índices de las columnas son los nombres de las columnas y los índices de las filas se pueden asignar manualmente o toman un valor automático, las columnas pueden ser de distintos tipos de datos

### Pandas Series

In [79]:
#importar libreria de pandas
import pandas as pd

In [82]:
# crear un panda serie con lista de jugadores de PSG y se asigna el indice
jugadores_psg = pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'],
          index=[1,7,10,30] # se asigna el indice a cada jugador
          )
jugadores_psg

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [83]:
# otra forma de crear una serie con indices es a partir de un diccionario {key:value} el key se vuelve indice
diccionario = {1:'Navas', 7:'Mbappe', 10:'Neymar', 30:'Messi'}
jugadores = pd.Series(diccionario)
jugadores

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

### Pandas DataFrame

In [84]:
# definir un DataFrame a partir de un diccionario
diccionario2 = {
    'jugador':['Navas', 'Mbappe', 'Neymar', 'Messi'],
    'altura':[183.0, 170.0, 170.0, 165.0],
    'goles':[2, 200, 200, 200]
}
diccionario2

{'jugador': ['Navas', 'Mbappe', 'Neymar', 'Messi'],
 'altura': [183.0, 170.0, 170.0, 165.0],
 'goles': [2, 200, 200, 200]}

In [86]:
# crear el dataframe
jugadores = pd.DataFrame(diccionario2, index=[1,7,10,30])
jugadores

jugador  altura  goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    200
30   Messi   165.0    200

In [87]:
# si no agrego los indices pandas los agrega con un consecutivo de cero hasta la cantidad de registros que tenga
jugadores = pd.DataFrame(diccionario2)
jugadores

jugador  altura  goles
0   Navas   183.0      2
1  Mbappe   170.0    200
2  Neymar   170.0    200
3   Messi   165.0    200

### Leer archivos con Pandas
* Leer un archivo csv pd.read_csv(ruta, sep=',', header=0) sep, indica el separador del csv, header indica la línea en donde se encuentran los encabezados si no tiene se pone None

In [91]:
# Leer un archivo csv que se encuentra en la misma carpeta del jupyternotebook
df_libros = pd.read_csv('./bestsellers-with-categories.csv')
df_libros

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [92]:
# obtener nombres de columnas
df_libros.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [93]:
# leer un json
pd.read_json('./hpcharactersdataraw.json')

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

### iloc y loc
Usados para navegar en un DataFrame, la l de loc significa que accede por label de la columna; la i de iloc significa que accede por índice de la columna se numeran desde cero
* .loc[inicio:fin]; muestra los registros de fila inicio hasta fila fin incluyéndola
* .loc[inicio:fin, [lista de campos]]; se pueden filtrar además nombres de columnas
* .loc[inicio:fin, [campo]] == 'condicion de campo'; para tener una lista de bool de los que cumplen la condición
* .loc[inicio:fin, [campo]] * operación; si el campo es numérico puedo hacer operaciones con el filtro realizado
* .iloc[inicio:fin, [ncolumna_i, ncolumna_f]]; muestra los resgitro de la fila inicio a la fila fin incluyendo la última fila, y las columnas i hasta la f menos 1



In [95]:
# slicing los primeros 4 registros
df_libros[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [96]:
# acceder por nombre de una columna
df_libros['Name']

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...                        
545         Wrecking Ball (Diary of a Wimpy Kid Book 14)
546    You Are a Badass: How to Stop Doubting Your Gr...
547    You Are a Badass: How to Stop Doubting Your Gr...
548    You Are a Badass: How to Stop Doubting Your Gr...
549    You Are a Badass: How to Stop Doubting Your Gr...
Name: Name, Length: 550, dtype: object

In [97]:
# acceder por nombre de dos o mas columnas
df_libros[['Name', 'Author']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  
0                    JJ Smith  
1                Stephen King  
2          Jordan B. Peterson  
3               George Orwell  
4    National Geographic Kids  
..                        ...  
545               Jeff Kinney  
546               Jen Sincero  
547               Jen Sincero  
548               Jen Sincero  
549               Jen Sincero  

[550 rows x 2 columns]

#### Uso de loc

In [100]:
# muestras los registros entre cero y cuatro incluyendo el cuatro
df_libros.loc[0:4]

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [102]:
# muestra los registros entre cero y cuatro de las columnas Name y Author
df_libros.loc[0:4,['Name', 'Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [104]:
# realizar una operacion con un campo numerico
df_libros.loc[:,['Reviews']] * -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [105]:
# validar que cumplen una condicion
df_libros.loc[:,['Author']] == 'JJ Smith'

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

#### uso de iloc

In [106]:
# devuelve todo el dataframe
df_libros.iloc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [107]:
# devuelve los todos los registros de las columnas cero a la tres, la numeracion de columnas empieza en cero
df_libros.iloc[:,0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

### Eliminar datos en Pandas

In [112]:
# crear una copia de df_libros
df_libros_copia = df_libros.copy()


In [113]:
# borrar columna sin afectar dataframe
df_libros_copia.drop('Genre', axis=1) # axis=1 es columna

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [114]:
# borrar columna en el mismo dataframe
df_libros_copia.drop('Genre', axis=1, inplace=True) # axis=1 es columna
df_libros_copia.head()


Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year  
0                  JJ Smith          4.7    17350      8  2016  
1              Stephen King          4.6     2052     22  2011  
2        Jordan B. Peterson          4.7    18979     15  2018  
3             George Orwell          4.7    21424      6  2017  
4  National Geographic Kids          4.8     7665     12  2019

In [115]:
# otra forma de borrar columnas usando drop es asignando de nuevo al dataframe
df_libros_copia = df_libros_copia.drop('Year', axis=1)
df_libros_copia

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  
0                    JJ Smith          4.7    17350      8  
1                Stephen King          4.6     2052     22  
2          Jordan B. Peterson          4.7    18979     15  
3               George Orwell          4.7    21424      6  
4    National Geographic Kids          4.8     7665     12  
..                        ...          ...      ...    ...  
545               Jeff Kinney          4.9     9413      8  
546               Jen Sincero          4.7    14331      8  
547               Jen Sincero          4.7    14331      8  
548               Jen Sincero          4.7    14331      8  
549               Jen Sincero          4.7    14331      8  

[550 rows x 5 columns]

In [120]:
# borrar la primera fila
print(df_libros_copia.drop(0, axis=0).head(3)) # axis=0 significa que borra la fila
df_libros_copia.head(4)

                                      Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  
1     2052     22  
2    18979     15  
3    21424      6  


Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  
0    17350      8  
1     2052     22  
2    18979     15  
3    21424      6

In [122]:
# borrar un rango de filas (0,10) y mostrar los tres primeros registros que quedan en el dataframe
print(df_libros_copia.drop(range(0,10), axis=0).head(3))

                                                 Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   
12                            A Stolen Life: A Memoir     Jaycee Dugard   

    User Rating  Reviews  Price  
10          4.6    23848      8  
11          4.6      460      2  
12          4.6     4149     32  


### Agregar datos con Pandas

In [123]:
# agregar columna nueva con NaN
df_libros_copia['nueva_columna'] = np.nan
df_libros_copia

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  nueva_columna  
0                    JJ Smith          4.7    17350      8            NaN  
1                Stephen King          4.6     2052     22            NaN  
2          Jordan B. Peterson          4.7    18979     15            NaN  
3               George Orwell          4.7    21424      6            NaN  
4    National Geographic Kids          4.8     7665     12            NaN  
..                        ...          ...      ...    ...            ...  
545               Jeff Kinney          4.9     9413      8            NaN  
546               Jen Sincero          4.7    14331      8            NaN  
547               Jen Sincero          4.7    14331      8            NaN  
548               Jen Sincero          4.7    14331      8            NaN  
549               Jen Sincero          4.7    14331      8            NaN  

[550 rows x 6 columns]

In [124]:
# obtener el numero de registros
df_libros_copia.shape[0]

550

In [125]:
# usar el numero de registros para crear un consecutivo
id = np.arange(0, df_libros_copia.shape[0])
id

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [126]:
# agregar consecutivo al dataframe
df_libros_copia['nuevo_consecutivo'] = id
df_libros_copia

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  nueva_columna  \
0                    JJ Smith          4.7    17350      8            NaN   
1                Stephen King          4.6     2052     22            NaN   
2          Jordan B. Peterson          4.7    18979     15            NaN   
3               George Orwell          4.7    21424      6            NaN   
4    National Geographic Kids          4.8     7665     12            NaN   
..                        ...          ...      ...    ...            ...   
545               Jeff Kinney          4.9     9413      8            NaN   
546               Jen Sincero          4.7    14331      8            NaN   
547               Jen Sincero          4.7    14331      8            NaN   
548               Jen Sincero          4.7    14331      8            NaN   
549               Jen Sincero          4.7    14331      8            NaN   

     nuevo_consecutivo  
0                    0  
1                    1  
2                    2  
3                    3  
4                    4  
..                 ...  
545                545  
546                546  
547                547  
548                548  
549                549  

[550 rows x 7 columns]

In [130]:
# agregar filas se hace con pd.concat
df_libros_copia = pd.concat([df_libros_copia, df_libros_copia], ignore_index=True)
df_libros_copia

Name  \
0                         10-Day Green Smoothie Cleanse   
1                                     11/22/63: A Novel   
2               12 Rules for Life: An Antidote to Chaos   
3                                1984 (Signet Classics)   
4     5,000 Awesome Facts (About Everything!) (Natio...   
...                                                 ...   
1095       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
1096  You Are a Badass: How to Stop Doubting Your Gr...   
1097  You Are a Badass: How to Stop Doubting Your Gr...   
1098  You Are a Badass: How to Stop Doubting Your Gr...   
1099  You Are a Badass: How to Stop Doubting Your Gr...   

                        Author  User Rating  Reviews  Price  nueva_columna  \
0                     JJ Smith          4.7    17350      8            NaN   
1                 Stephen King          4.6     2052     22            NaN   
2           Jordan B. Peterson          4.7    18979     15            NaN   
3                George Orwell          4.7    21424      6            NaN   
4     National Geographic Kids          4.8     7665     12            NaN   
...                        ...          ...      ...    ...            ...   
1095               Jeff Kinney          4.9     9413      8            NaN   
1096               Jen Sincero          4.7    14331      8            NaN   
1097               Jen Sincero          4.7    14331      8            NaN   
1098               Jen Sincero          4.7    14331      8            NaN   
1099               Jen Sincero          4.7    14331      8            NaN   

      nuevo_consecutivo  
0                     0  
1                     1  
2                     2  
3                     3  
4                     4  
...                 ...  
1095                545  
1096                546  
1097                547  
1098                548  
1099                549  

[1100 rows x 7 columns]

### Manejo de datos nulos

In [131]:
# crear un dataframe con valores NaN y None
dict_pd = {
    'col1':[1, 2, 3, np.nan],
    'col2':[4, np.nan, 6,7],
    'col3':['a','b', 'c', None]
}
df = pd.DataFrame(dict_pd)
df

col1  col2  col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [132]:
# saber si es NaN o None
df.isnull()

col1   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [134]:
# cambiar por 1 si es nulo
df.isnull() *1


col1  col2  col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [135]:
# llenar con palabra o valor especifico
df.fillna('faltante')

col1      col2      col3
0       1.0       4.0         a
1       2.0  faltante         b
2       3.0       6.0         c
3  faltante       7.0  faltante

In [143]:
# fillna recibe tambien funciones como media, maximo, minimo,etc
df.fillna(df.mean(numeric_only=True))

col1      col2  col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [145]:
# otra forma de llenar NaN con interpolate
df.interpolate()

col1  col2  col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [146]:
# se pueden borrar los NaN, se debe tener cuidado porque borra toda la fila en caso de que haya un NaN
df.dropna()

col1  col2 col3
0   1.0   4.0    a
2   3.0   6.0    c